### ISSUE TITLE
Notifications don't have dark backgrounds

### ISSUE THREAD

**Issue by eviltak** [SpiritCroc/DefaultDarkTheme-oms#1]
Notifications on OnePlus One + Resurrection Remix v5.8.1 do not have dark backgrounds. I don't know if this is by design or if it is not implemented. If it is the latter, I can help getting this themed. Thanks for the awesome theme!

**Comment by SpiritCroc** [comment]
That's by design, as some apps depend on having a light bg in order to remain readable. I was planning to add it as a variant (so you can optionally enable it) and already have a commit lying around, but it's not finished yet. Will probably look into it soon now that you mention it. Thanks for offering help :)

**Comment by SpiritCroc** [comment]
@eviltak Pushed what I currently have to a new branch, so you can continue/finish it if you want; TODOs are in the commit message:
https://github.com/SpiritCroc/DefaultDarkTheme-oms/commit/2ff9144d927646d79d6dadc19da0803b9b496a1d

**Comment by SpiritCroc** [comment]
UPDATE: Finished it, will be published with the next release

**Comment by eviltak** [comment]
Good work, thanks! You can close this issue if you think it appropriate.

**Comment by SpiritCroc** [comment]
Sure, keeping it open on purpose until commit is pushed

**Comment by SpiritCroc** [comment]
In case you're interested in why it takes some more time then usual for me to push ;)
http://review.projektsubstratum.com/#/c/291/
