### ISSUE TITLE
Dark colors in the notifications

### ISSUE THREAD

**Issue by KabbAmine** [SpiritCroc/DefaultDarkTheme-oms#2]
First of all, thanks for your wonderful theme.

Everything's looking good except some apps that use dark colors on notifications.

See:

![here](http://i.imgur.com/u3crSMT.jpg)

* The buttons of Vanilla music
* The mail title when expanded for K9-mail.
 
I'm not sure if its related to the theme or the app itself.

**Comment by SpiritCroc** [comment]
The problems is that some applications put their own colors into notifications, expecting the notifications to have a light background. That's the reason why I didn't make notifications dark for a long time.

One could try to additionally theme all the concerned apps, but I decided to only theme apps that I personally use, and I also don't feel like adding a bunch of apps to the theme that aren't actually themed apart from the notifications (so not themed at all if you selected light notification background).

So a fix from my side is unlikely to happen, but I'm open for pull requests ;) (just make sure it's a variant if it breaks light notifications otherwise)

**Comment by KabbAmine** [comment]
That was quick.

Thanks for the explanation, I will take a look  when having time, probably after a few months.
