### ISSUE TITLE
Samsung support

### ISSUE THREAD

**Issue by AD2076** [SpiritCroc/DefaultDarkTheme-oms#3]
Will you add It?

**Comment by SpiritCroc** [comment]
No, I don't have any devices to test this, and not intending to change that.
I'm open for contributions, though, if anybody wants

**Comment by AD2076** [comment]
I am available for testing. I have an S8+

**Comment by SpiritCroc** [comment]
This is a free and open theme that I do in my free time.
I don't earn anything from it (I even put more into it than I get back).
I don't see why I should add support for something I myself would never need.

Sure, I could try getting it to run with other persons as testers, but this is a lot more time consuming than normal, which also can take quite some time, and I personally don't have anything from it; that's why I meant: I'm open for contributions, people can install it on their Samsungs, see what happens and fix the issues, but I won't do it.

I hope you understand :)

**Comment by aletheus** [comment]
I'm willing to build and test. I have the tab S3, and I would love to work on this. I have General experience with Linux and GitHub. But I'm not sure where to start as far as looking around and where problems may lie. If I could get some general directions from you, then I'd know where to start. I've messed around with code, but I'm not a developer by any stretch of the imagination. And that doesn't mean I'm not willing to work on it. I know the first place I should look is the error logs. And I should probably have the substratum theme engine working properly first. So let me do some research and I'll get back to you as to where I feel like maybe the problems lie. I'm so glad that you even have this open source. Not that I'm not willing to pay the $2 for other people's themes, but that just doesn't support the spirit of community. I'd much rather do the work and contribute to everyone's enjoyment, then contribute $2 to somebody's closed-source solution. I'm sure most Samsung owners would rather just pay the $2. It's a lot easier. But I'm wanting to get deeper into custom ROM building as it is. And I feel like maybe this would be a good place to start.

**Comment by SpiritCroc** [comment]
Great to hear you like open source :)

Best way to add support for stock ROMs would probably be:
- Try out what works already and what does not
- In case of crashes: logcat, find the overlay/resource causing this
- In case of missing overlays (incomplete theming): When approaching something closed-source like Samsung applications or framework, you will probably need to decompile it in order to get an idea about what's needed. That's where I don't have much experience (which does not mean none) since if you look at the theme in its current form, it mostly overlays open source applications where you can actually look at what overlays are needed, or even create pull-requests and alike to expose previously hard-coded colors.

For general theming instructions, there should be guides out there on how to start and how substratum works.

If you plan on using custom ROMs on your Samsung device, this is unrelated to this issue - custom ROMs are supported by this theme irrelevant of the exact device as long as they're up-to-date with substratum exposure commits.
