### ISSUE TITLE
[Request] Coloured status bar in settings

### ISSUE THREAD

**Issue by AdrianVovk** [SpiritCroc/DefaultDarkTheme-oms#8]
Could you put some color into the settings status bar? The difference between #212121 and pure black doesn't look too good (too much of a contrast). It just should be a two-line fix (styles.xml, and colors.xml), but I might be mistaken

**Comment by SpiritCroc** [comment]
Basically, the main aim of this theme is to replace Theme.Material.Light with Theme.Material.
Since Theme.Material uses #212121 as actionbar bg, that's what I use.

Actually, it looks fine for me, even with black background (which is just an additional variant, not the main focus, which is #303030).

I don't think I'll change this, but which color would you suggest? I don't see how it's currently "too much contrast", use less contrast and it would be the same color, is it that what you want?

**Comment by AdrianVovk** [comment]
Sorry for taking so long to reply. I've been swamped with homework lately. Anyways, here is what settings looks like now:
![settings](https://user-images.githubusercontent.com/11251606/31550171-73ccb914-affe-11e7-9c66-2543709e1aca.png)

And here is what I'd change it to.
![settings-modded](https://user-images.githubusercontent.com/11251606/31550237-ac2aebd2-affe-11e7-81e5-f33f9612dbb8.png)
Here the status bar is #161616

**Comment by SpiritCroc** [comment]
Ah now I get what you're saying, sorry for misreading.
My reasoning is still valid though, it's pure black in Theme.Material, so that's what I use here. You're free to use your own fork of course.
If you want to change that color for more than settings, you could probably also look into overlaying the primary_dark_material_dark color in the android package.
