### ISSUE TITLE
Pixel App drawer Navbar still changes its color to black

### ISSUE THREAD

**Issue by jwannebo** [SpiritCroc/DefaultDarkTheme-oms#9]
The default behavior on the Pixel launcher is to have a white background for the app drawer, with the navigation and status bar icons swapped to black to be legible. In this theme, the drawer background changes to a dark color, but the default behavior of swapping the navbar and status bar icons to black isn't overridden, making them invisible.
![screen](https://user-images.githubusercontent.com/5732947/30442533-bb1e9316-994a-11e7-93d1-4d37b43ce159.png)

**Comment by SpiritCroc** [comment]
Reminds me of https://github.com/SpiritCroc/DefaultDarkTheme-oms/commit/2537b389c144b2893a16e76170f5acc246480521, will push the patch for pixel launcher later. Unfortunately, black navigation/status bar in drawer are hardcoded (in AOSP launcher at least, so I guess in Pixel launcher as well, but I'm too lazy to verify since I don't use it either way), so either live with black on dark in status bar or have a light drawer (workaround for making navigation bar bg light while keeping dark drawer is possible & in though)
